# Generated by Django 2.2.10 on 2020-03-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_ranges', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('international_country_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalHealthSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_term', models.TextField()),
                ('common_term', models.TextField()),
                ('external_classification_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(blank=True)),
                ('postcode', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.AgeRanges')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('questiontype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.QuestionType')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('current_location', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Location')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.ParticipantLocation'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Region'),
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.GlobalHealthSchema')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.ParticipantLocation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.ParticipantLocation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_Answer', models.IntegerField()),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('freeform_text', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Question')),
            ],
        ),
    ]
