# Generated by Django 2.2.10 on 2020-03-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWarningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warninglevel', models.IntegerField(null=True)),
                ('warningadvice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'questiontype')},
        ),
        migrations.RemoveField(
            model_name='participantlocation',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='participantlocation',
            name='participant_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='dateAnswered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='trackingKey',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='alias',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='style',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dateFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dateTo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='freeform_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='scale_Answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participantlocation',
            name='dateFrom',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participantlocation',
            name='dateTo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HealthWarningTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warninglevel', models.IntegerField(null=True)),
                ('warningadvice', models.TextField()),
                ('mininclusive', models.IntegerField(null=True)),
                ('maxinclusive', models.IntegerField(null=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Jurisdiction')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAnswered', models.DateTimeField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answerset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questionadmin.AnswerSet'),
        ),
    ]
