# Generated by Django 2.2.10 on 2020-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionadmin', '0003_auto_20200315_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantlocation',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='participantlocation',
            name='participant_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='dateFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dateTo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='freeform_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='scale_Answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participantlocation',
            name='dateFrom',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participantlocation',
            name='dateTo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
